<form class="form customform"
      action="<?php echo $this->getFormAction(); ?>"
      id="seller-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      enctype="multipart/form-data"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">    	
        <div class="field first_name required">
            <label class="label" for="first_name"><span><?= $block->escapeHtml(__('First name:')) ?></span></label>
            <div class="control">
                <input name="first_name" 
                       id="first_name" 
                       title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" 
                       class="input-text" 
                       type="text" 
                       data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field last_name required">
            <label class="label" for="last_name"><span><?= $block->escapeHtml(__('Last name:')) ?></span></label>
            <div class="control">
                <input name="last_name" 
                       id="last_name" 
                       title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" 
                       class="input-text" 
                       type="text" 
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" 
                       id="email" 
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text" 
                       type="email" 
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field phone required">
            <label class="label" for="phone"><span><?= $block->escapeHtml(__('Phone:')) ?></span></label>
            <div class="control">
                <input name="phone" id="phone" title="<?= $block->escapeHtmlAttr(__('Phone')) ?>" class="input-text" type="text" data-validate="{required:true, 'validate-number':true}">
            </div>
        </div>
        
       
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
    </div>
</form>
